<?php
/**
 * ChargeAfter
 *
 * @category    Payment Gateway
 * @package     Chargeafter_Payment
 * @copyright   Copyright (c) 2021 ChargeAfter.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author      taras@lagan.com.ua
 */

?>
<script type="text/x-magento-init">
    {
        "*": {
            "Chargeafter_Payment/js/widget": {
                "cdnUrl": "<?= /* @noEscape */ $block->getCdnUrl() ?>",
                "caConfig": {
                    "apiKey": "<?= /* @noEscape */ $block->getPublicKey() ?>"
                }
            }
        }
    }
</script>
<?php
$widget_type = $block->getData('type');
if (in_array($widget_type, ['product-widget','product-widget-line-of-credit','product-widget-installments','default-template'])
    && !$product = $block->getProduct()) {
    $widget_type = '';
}

$output = "<div class=\"ca-promotional-widget\"";
$output .= " data-widget-type=\"$widget_type\"";
$output .= " data-widget-mode=\"{$block->getData('mode')}\"";
if (in_array($widget_type, ['product-widget','product-widget-line-of-credit','product-widget-installments','default-template'])) {
    $output .= " data-widget-item-sku=\"{$product->getSku()}\" data-widget-item-price=\"{$product->getFinalPrice()}\"";
}
if ($block->getData('financing_page_url')) {
    $output .= " data-widget-financing-page-url=\"{$block->getData('financing_page_url')}\"";
}
$output .= "></div>";

/* @noEscape */ echo $output;
