<?php
/**
 * ChargeAfter
 *
 * @category    Payment Gateway
 * @package     Chargeafter_Payment
 * @copyright   Copyright (c) 2021 ChargeAfter.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author      taras@lagan.com.ua
 *
 * @var $block \Chargeafter\Payment\Block\PromotionalWidgetBlock
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Chargeafter_Payment/js/widget": <?= /* @noEscape */ $block->getComponentJsonConfig() ?>
        }
    }
</script>
<?php
$widget_type = $block->getData('type');
$widget_mode = $block->getData('mode');

$product_widgets = ['product-widget','product-widget-line-of-credit','product-widget-installments','default-template'];

$product = $block->getProduct();
$cart = $block->getCart();

if (in_array($widget_type, $product_widgets) && (!$product && !$cart)) {
    $widget_type = '';
}

$output = "<div class=\"ca-promotional-widget\" style=\"margin:5px 0\"";
$output .= " data-widget-type=\"$widget_type\"";
$output .= " data-widget-mode=\"$widget_mode\"";

if (in_array($widget_type, $product_widgets)) {
    $widget_item_tag = $block->getData('tag');
    $financing_page_url = $block->getData('financing_page_url');

    if ($product) {
        $product_sku = $product->getSku();
        $product_price = $product->getFinalPrice();

        $output .= " data-widget-item-sku=\"$product_sku\" data-widget-item-price=\"$product_price\"";
    }

    if ($cart) {
        $cart_sku = 'cart_sku';
        $cart_price = $cart->getGrandTotal();

        $output .= " data-widget-item-sku=\"$cart_sku\" data-widget-item-price=\"$cart_price\"";
    }

    if ($widget_item_tag) {
        $output .= " data-widget-item-tag=\"{$widget_item_tag}\"";
    }

    if ($financing_page_url) {
        $output .= " data-widget-financing-page-url=\"{$financing_page_url}\"";
    }
}

$output .= "></div>";

/* @noEscape */ echo $output;
